### ISSUE TITLE
Link on header in installed plugins not working

### ISSUE THREAD

**Issue by lastlink** [enricofrigo/kanboard#2]
Maybe getPluginHomepage() or something else is not working
![notworkingheaderlink](https://user-images.githubusercontent.com/6679425/40247444-6648cf52-5a9a-11e8-93d3-4bd6b6b863b8.png)

**Comment by enricofrigo** [comment]
fixed

**Comment by lastlink** [comment]
could you do a new release then? Thanks!

**Comment by enricofrigo** [comment]
done
